# Generated by Django 5.0.3 on 2024-04-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ween',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('anons', models.CharField(max_length=250, verbose_name='фамилия')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
