# Generated by Django 5.0.3 on 2024-04-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ween',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='ween',
            name='price',
            field=models.CharField(default=2, max_length=250, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ween',
            name='anons',
            field=models.CharField(max_length=250, verbose_name='Добавить описание'),
        ),
    ]
