# Generated by Django 5.0.3 on 2024-07-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ween_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_list',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
