# Generated by Django 5.0.3 on 2024-05-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ween_image_book_list_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ween',
            name='available_seats',
            field=models.IntegerField(default=50, verbose_name='Доступные места'),
        ),
    ]
