# Generated by Django 5.0.3 on 2024-07-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_list_is_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='ween',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
